name: Json to env

on:
  push:
    branches:
      - 'step-7'
    tags:
      - '**'

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch and update json config
        run: |
          curl https://static.dev.liber.casa/build/environments/env.json -o env.json
          git add env.json
          git commit -m "Update env"
          git push

      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'env.json'
          prefix: VUE_APP

      - name: Use env vars from json
        run: |
          echo "Multi language = ${{ env.VUE_APP_MULTI_LANGUAGE }}, + ${{ env.VUE_APP_OPTIONS }}"
