name: Json to env

on:
  push:
    branches:
      - 'step-7'
    tags:
      - '**'

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch json config
        run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://static.dev.liber.casa/build/environments/env.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

#      - name: Checkout
#        uses: actions/checkout@v2

      - name: Use env vars from json
        run: |
          echo "Multi language = ${{ env.JSON_RESPONSE.MULTI_LANGUAGE }}"
